# Generated by Django 4.2.26 on 2025-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='answer_key',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
