# Generated by Django 5.2.8 on 2025-11-27 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_father_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='students.batch'),
        ),
    ]
